### ISSUE TITLE
faktory-1.1.3.2 fails to build with crypton-1.1 and ram

### ISSUE THREAD

**Issue by juhp** [freckle/faktory_worker_haskell#132]
```
       Building library for faktory-1.1.3.2...
       [ 1 of 20] Compiling Data.Pool.Compat
       [ 2 of 20] Compiling Faktory.Prelude
       [ 3 of 20] Compiling Faktory.JobState
       [ 4 of 20] Compiling Faktory.JobFailure
       [ 5 of 20] Compiling Faktory.Job.Custom
       [ 6 of 20] Compiling Faktory.Protocol
       [ 7 of 20] Compiling Network.Connection.Compat
       [ 8 of 20] Compiling Faktory.Connection
       [ 9 of 20] Compiling Faktory.Settings.Queue
       [10 of 20] Compiling Faktory.JobOptions
       [11 of 20] Compiling Faktory.Settings
       [12 of 20] Compiling Faktory.Client
       /home/curators/work/unpack-dir/unpacked/faktory-1.1.3.2-b87029c0e2c86833e84b8c60efa582429f9a7394b6a3936d461110971f3c5554/library/Faktory/Client.hs:194:21: error: [GHC-39999]
           • No instance for ‘ByteArrayAccess (Digest SHA256)’
               arising from a use of ‘hash’
           • In the second argument of ‘times’, namely ‘hash’
             In the first argument of ‘(.)’, namely ‘times (n - 1) hash’
             In the second argument of ‘(.)’, namely
               ‘times (n - 1) hash . hash . T.encodeUtf8’
           |
       194 |     . times (n - 1) hash
           |                     ^^^^

       /home/curators/work/unpack-dir/unpacked/faktory-1.1.3.2-b87029c0e2c86833e84b8c60efa582429f9a7394b6a3936d461110971f3c5554/library/Faktory/Client.hs:205:10: error: [GHC-39999]
           • Could not deduce ‘ram-0.22.0:Data.ByteArray.Types.ByteArrayAccess
                                 b’
               arising from a use of ‘hashWith’
             from the context: ByteArrayAccess b
               bound by the type signature for:
                          hash :: forall b. ByteArrayAccess b => b -> Digest SHA256
               at library/Faktory/Client.hs:204:3-49
             Possible fix:
               add (ram-0.22.0:Data.ByteArray.Types.ByteArrayAccess
                      b) to the context of
                 the type signature for:
                   hash :: forall b. ByteArrayAccess b => b -> Digest SHA256
           • In the expression: hashWith SHA256
             In an equation for ‘hash’: hash = hashWith SHA256
             In an equation for ‘hashPassword’:
                 hashPassword nonce n password
                   = pack . show . times (n - 1) hash . hash . T.encodeUtf8
                       $ pack password <> nonce
                   where
                       hash :: ByteArrayAccess b => b -> Digest SHA256
                       hash = hashWith SHA256
           |
       205 |   hash = hashWith SHA256
           |          ^^^^^^^^
```

**Comment by pbrisbin** [comment]
Thanks, I've reproduced the error with the following `stack-nightly.yaml`:

```yaml
resolver: nightly-2026-06-28

extra-deps:
  - crypton-1.1.4
  - crypton-connection-0.4.6
  - crypton-x509-1.9.1
  - crypton-x509-store-1.9.0
  - crypton-x509-system-1.9.0
  - crypton-x509-validation-1.9.1
  - hpke-0.1.0
  - mlkem-0.2.2.0
  - tls-2.4.3
```

It does not reproduce on `nightly-2026-06-28` alone.

**Comment by pbrisbin** [comment]
So, the fix is relatively simple: to replace `memory` with `ram`. But then we don't simultaneously build with old `crypton`, and it's not as easy as some CPP in the code; it would have to be a build flag to switch deps or something, maybe add bounds, I don't know.

Or we could drop support for all the old stuff. I guess I'm OK with that, but not this early. I feel like we wouldn't want the _only_ buildable set to be nightly, which is what would happen if we do that now. But if we don't build in nightly, we fall out and risk missing an LTS. Kind of a crappy spot to be in.

**Comment by juhp** [comment]
I agree it is a little painful, but yeah I don't see another way forward.
Though older versions will continue to build in lts of course.

As such an accompanying major version bump could make sense for some packages.

**Comment by pbrisbin** [comment]
This was fixed in #133, but the release failed. That'll be fixed in #135 and should release 1.2.0.0 which addresses this. I will close this issue once that happens.

@juhp once a fixed version is available on Hackage, is coming back into Stackage automated, or will I have to take some action there?
