### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [freckle/faktory_worker_haskell#82]
```
faktory                   > /tmp/stack-24fe4420f69da4df/faktory-1.1.2.0/library/Faktory/Job/Custom.hs:32:23: error:
faktory                   >     • Couldn't match type: HashMap.HashMap k0 v0
faktory                   >                      with: Data.Aeson.KeyMap.KeyMap Value
faktory                   >       Expected: Object
faktory                   >         Actual: HashMap.HashMap k0 v0
faktory                   >     • In the second argument of ‘($)’, namely ‘HashMap.union b a’
faktory                   >       In the second argument of ‘($)’, namely
faktory                   >         ‘Object $ HashMap.union b a’
faktory                   >       In the expression: Custom $ Object $ HashMap.union b a
faktory                   >    |
faktory                   > 32 |     Custom $ Object $ HashMap.union b a
faktory                   >    |                       ^^^^^^^^^^^^^^^^^
faktory                   > 
faktory                   > /tmp/stack-24fe4420f69da4df/faktory-1.1.2.0/library/Faktory/Job/Custom.hs:32:37: error:
faktory                   >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
faktory                   >                      with: HashMap.HashMap k0 v0
faktory                   >       Expected: HashMap.HashMap k0 v0
faktory                   >         Actual: Object
faktory                   >     • In the first argument of ‘HashMap.union’, namely ‘b’
faktory                   >       In the second argument of ‘($)’, namely ‘HashMap.union b a’
faktory                   >       In the second argument of ‘($)’, namely
faktory                   >         ‘Object $ HashMap.union b a’
faktory                   >    |
faktory                   > 32 |     Custom $ Object $ HashMap.union b a
faktory                   >    |                                     ^
faktory                   > 
faktory                   > /tmp/stack-24fe4420f69da4df/faktory-1.1.2.0/library/Faktory/Job/Custom.hs:32:39: error:
faktory                   >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
faktory                   >                      with: HashMap.HashMap k0 v0
faktory                   >       Expected: HashMap.HashMap k0 v0
faktory                   >         Actual: Object
faktory                   >     • In the second argument of ‘HashMap.union’, namely ‘a’
faktory                   >       In the second argument of ‘($)’, namely ‘HashMap.union b a’
faktory                   >       In the second argument of ‘($)’, namely
faktory                   >         ‘Object $ HashMap.union b a’
faktory                   >    |
faktory                   > 32 |     Custom $ Object $ HashMap.union b a
faktory                   >    |                                       ^
```
